name: ui
description: Dart package which manages the deck domain.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #flutter
  flutter:
    sdk: flutter
    
dev_dependencies:
  pedantic: ^1.11.0
